name: schedulo

services:
    mysqldb:
        image: mysql:8.4
        container_name: schedulo-mysql
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: schedule
        ports:
            - "3306:3306"
        volumes:
            - mysql_data:/var/lib/mysql
            - ./init.sql:/docker-entrypoint-initdb.d/init.sql

    backend:
        build:
            context: ./Back_end
            dockerfile: Dockerfile
        image: schedulo-backend:latest
        container_name: schedulo-backend
        restart: always
        ports:
            - "4000:4000"
        environment:
            - DB_HOST=mysqldb
            - DB_PORT=3306
            - DB_USER=root
            - DB_PASSWORD=root
            - DB_NAME=schedule
            - PORT=4000
            - JWT_SECRET=${JWT_SECRET:-9332323b81bda060b0f4bef9c8cf3b3f6ef4af192940d23d0624a7bf678cc8c0}
        volumes:
            - ./Back_end/image:/app/image
            - ./Back_end/CV:/app/CV
        depends_on:
            - mysqldb

    frontend:
        build:
            context: ./Front_end
            dockerfile: Dockerfile
        image: schedulo-frontend:latest
        container_name: schedulo-frontend
        restart: always
        ports:
            - "8000:80"
        depends_on:
            - backend

volumes:
    mysql_data:
