version: '3.8'

services:
  mysqldb:
    image: mysql:8.4
    container_name: schedulo-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: schedule
    ports:
      - "3308:3306"
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: schedulo-app
    restart: always
    ports:
      - "4000:4000"
    environment:
      - DB_HOST=mysqldb
      - DB_PORT=3306
      - DB_USER=root
      - DB_PASSWORD=root
      - DB_NAME=schedule
      - PORT=4000
    volumes:
      - ./Back_end/image:/app/Back_end/image
      - ./Back_end/CV:/app/Back_end/CV
    depends_on:
      - mysqldb

volumes:
  mysql_data:
